# Generated by Django 3.0.5 on 2021-03-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='_id',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
