# Generated by Django 3.0.5 on 2021-03-05 18:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20210305_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='_id',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='id2',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
