# Generated by Django 3.0.5 on 2021-03-05 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20210305_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='id2',
            new_name='_id',
        ),
    ]
