# Generated by Django 3.0.5 on 2021-03-05 20:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_auto_20210305_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='_id',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='id2',
            field=models.CharField(default=uuid.UUID('612ef7f5-b8f5-4c6f-b840-6aa30e8ee89b'), max_length=200, unique=True),
        ),
    ]
