# Generated by Django 3.0.5 on 2021-03-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_auto_20210305_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='id2',
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='email',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
