# Generated by Django 3.0.5 on 2021-03-05 21:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_auto_20210305_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='id2',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
