# Generated by Django 3.0.5 on 2021-03-05 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_userdetails_id2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='id2',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='_id',
            field=models.CharField(default=1, max_length=100, unique=True),
        ),
    ]
