# Generated by Django 3.0.5 on 2021-03-05 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_auto_20210305_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='_id',
        ),
    ]
