# Generated by Django 3.0.5 on 2021-03-05 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0010_remove_userdetails__id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_content', models.TextField(blank=True)),
                ('heading', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
