# Generated by Django 3.0.5 on 2021-03-06 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0012_userdetails_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='created_at',
        ),
    ]
