# Generated by Django 3.0.5 on 2021-03-06 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0014_servicescontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageURL', models.TextField(blank=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(blank=True, max_length=20)),
                ('author', models.CharField(blank=True, max_length=40)),
                ('dateDay', models.CharField(blank=True, max_length=2)),
                ('dateMonth', models.CharField(blank=True, max_length=3)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
