# Generated by Django 3.0.5 on 2021-03-07 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0015_blogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
