# Generated by Django 3.0.5 on 2021-03-14 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0017_servicesoffered_servicesofferedcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesOfferedContent2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageURL', models.TextField(blank=True)),
                ('services_Name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='ServicesOfferedContent',
            new_name='ServicesOfferedContent1',
        ),
    ]
