# Generated by Django 3.0.5 on 2021-03-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0018_auto_20210313_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageURL', models.TextField(blank=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
