# Generated by Django 3.0.5 on 2021-03-15 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0019_servicesdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section1_heading', models.CharField(blank=True, max_length=100)),
                ('section1_content', models.TextField(blank=True)),
                ('section2_heading', models.CharField(blank=True, max_length=200)),
                ('section2_content', models.TextField(blank=True)),
                ('section3_heading', models.CharField(blank=True, max_length=100)),
                ('section3_content', models.TextField(blank=True)),
                ('section3_percentage1', models.CharField(blank=True, max_length=100)),
                ('section3_percentage2', models.CharField(blank=True, max_length=100)),
                ('section3_percentage3', models.CharField(blank=True, max_length=100)),
                ('section4_heading', models.CharField(blank=True, max_length=100)),
                ('section4_content', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Services',
        ),
        migrations.DeleteModel(
            name='ServicesOffered',
        ),
    ]
