# Generated by Django 3.0.5 on 2021-03-15 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0020_auto_20210315_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='section3_percentage1_heading',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='section3_percentage2_heading',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='section3_percentage3_heading',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
