# Generated by Django 3.0.5 on 2021-03-15 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0021_auto_20210315_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='section5_imageURL',
            field=models.TextField(blank=True),
        ),
    ]
