# Generated by Django 3.0.5 on 2021-03-15 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0022_homepagecontent_section5_imageurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagecontent',
            name='section3_heading',
        ),
    ]
