# Generated by Django 3.0.5 on 2021-03-16 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0023_remove_homepagecontent_section3_heading'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServicesContent',
        ),
    ]
