# Generated by Django 3.0.5 on 2021-03-20 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0024_delete_servicescontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='banner_image1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='banner_image2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='banner_image3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='section2_imageURL',
            field=models.TextField(blank=True),
        ),
    ]
