# Generated by Django 3.0.5 on 2021-03-20 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0025_auto_20210320_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='banner1_caption',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='banner1_h1',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='banner2_caption',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='banner2_h1',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='banner3_caption',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='banner3_h1',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
