# Generated by Django 3.0.5 on 2021-03-20 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0026_auto_20210320_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecontent',
            name='banner1_caption',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='banner1_h1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='banner2_caption',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='banner2_h1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='banner3_caption',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='banner3_h1',
            field=models.TextField(blank=True),
        ),
    ]
